// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ttnru5VbLUEMRZOpclHNG22a9AHUpYI',
    appId: '1:1072820384109:web:0fea72d463afd21c67ea64',
    messagingSenderId: '1072820384109',
    projectId: 'mobile-tcc-4aea2',
    authDomain: 'mobile-tcc-4aea2.firebaseapp.com',
    storageBucket: 'mobile-tcc-4aea2.firebasestorage.app',
    measurementId: 'G-YPREVM3FYS',
    databaseURL: 'https://mobile-tcc-4aea2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpu5EmM5XD8LaZ_P2Y4QQYHBsH6zFwo0',
    appId: '1:1072820384109:android:ebcf48c646626f1067ea64',
    messagingSenderId: '1072820384109',
    projectId: 'mobile-tcc-4aea2',
    storageBucket: 'mobile-tcc-4aea2.firebasestorage.app',
    databaseURL: 'https://mobile-tcc-4aea2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7syeWAPTXGrsXBrw8b5WC0UTHzRMgaA',
    appId: '1:1072820384109:ios:ff0f2f466bc500f767ea64',
    messagingSenderId: '1072820384109',
    projectId: 'mobile-tcc-4aea2',
    storageBucket: 'mobile-tcc-4aea2.firebasestorage.app',
    iosBundleId: 'com.example.mobileTcc',
    databaseURL: 'https://mobile-tcc-4aea2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7syeWAPTXGrsXBrw8b5WC0UTHzRMgaA',
    appId: '1:1072820384109:ios:ff0f2f466bc500f767ea64',
    messagingSenderId: '1072820384109',
    projectId: 'mobile-tcc-4aea2',
    storageBucket: 'mobile-tcc-4aea2.firebasestorage.app',
    iosBundleId: 'com.example.mobileTcc',
    databaseURL: 'https://mobile-tcc-4aea2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ttnru5VbLUEMRZOpclHNG22a9AHUpYI',
    appId: '1:1072820384109:web:74a0a0b8538bc0f767ea64',
    messagingSenderId: '1072820384109',
    projectId: 'mobile-tcc-4aea2',
    authDomain: 'mobile-tcc-4aea2.firebaseapp.com',
    storageBucket: 'mobile-tcc-4aea2.firebasestorage.app',
    measurementId: 'G-P4RLP57E0W',
    databaseURL: 'https://mobile-tcc-4aea2-default-rtdb.firebaseio.com',
  );
}
